### ISSUE TITLE
Where to find the "AP News dataset"?

### ISSUE THREAD

**Issue by vijayrudraraju** [meta-toolkit/metapy#1]
Used in the 2-search-and-ir-eval.ipynb tutorial. Can't seem to find it, even though github runs the notebook fine! :confused:

**Comment by megado123** [comment]
I "think" wget http://sifaka.cs.uiuc.edu/ir/textdatabook/apnews.tar.gz

**Comment by vijayrudraraju** [comment]
@megado123 A belated thanks! 🙇
